"""empty message

Revision ID: 17125518162f
Revises: 9aac228f9107
Create Date: 2024-03-05 12:53:02.048190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17125518162f'
down_revision = '9aac228f9107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
