"""empty message

Revision ID: 250ec41311da
Revises: cd6aaf2cf368
Create Date: 2024-02-09 06:24:43.865674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250ec41311da'
down_revision = 'cd6aaf2cf368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_gamer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gamers', ['best_gamer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('best_gamer_id')

    # ### end Alembic commands ###
