"""empty message

Revision ID: 3659b175ceca
Revises: dc79b06012c5
Create Date: 2024-02-09 03:06:16.797756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3659b175ceca'
down_revision = 'dc79b06012c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('losers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lost_games_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['gamers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viewed_games_count', sa.Integer(), nullable=False),
    sa.Column('best_gamer', sa.Integer(), nullable=True),
    sa.Column('worst_gamer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['best_gamer'], ['gamers.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worst_gamer'], ['losers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewers')
    op.drop_table('losers')
    # ### end Alembic commands ###
