"""empty message

Revision ID: 3f9eb5c50189
Revises: 250ec41311da
Create Date: 2024-02-09 06:30:56.626746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9eb5c50189'
down_revision = '250ec41311da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gamers', schema=None) as batch_op:
        batch_op.drop_constraint('gamers_viewer_id_fkey', type_='foreignkey')
        batch_op.drop_column('viewer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gamers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('gamers_viewer_id_fkey', 'viewers', ['viewer_id'], ['id'])

    # ### end Alembic commands ###
