"""empty message

Revision ID: 579623acb974
Revises: 3659b175ceca
Create Date: 2024-02-09 05:58:57.897891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579623acb974'
down_revision = '3659b175ceca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gamer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('viewers_best_gamer_fkey', type_='foreignkey')
        batch_op.drop_constraint('viewers_worst_gamer_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gamers', ['gamer_id'], ['id'])
        batch_op.drop_column('best_gamer')
        batch_op.drop_column('worst_gamer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worst_gamer', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('best_gamer', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('viewers_worst_gamer_fkey', 'losers', ['worst_gamer'], ['id'])
        batch_op.create_foreign_key('viewers_best_gamer_fkey', 'gamers', ['best_gamer'], ['id'])
        batch_op.drop_column('gamer_id')

    # ### end Alembic commands ###
