"""empty message

Revision ID: cd6aaf2cf368
Revises: 211231736e7c
Create Date: 2024-02-09 06:17:31.562443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6aaf2cf368'
down_revision = '211231736e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewers', schema=None) as batch_op:
        batch_op.drop_constraint('viewers_gamer_id_fkey', type_='foreignkey')
        batch_op.drop_column('gamer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gamer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('viewers_gamer_id_fkey', 'gamers', ['gamer_id'], ['id'])

    # ### end Alembic commands ###
